language: python

dist: xenial

python:
  - "2.7"

addons:
  firefox: latest

services:
  - redis-server
  - xvfb

before_install:
  - gem install foreman
  - pip install -r dev_requirements.txt
  # Adapted from https://github.com/pytest-dev/pytest-selenium/blob/a5ed7d08dea00b9cffb6df3beac8d70517e9de4c/.travis.yml#L40-L45
  - curl -L -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH
  - geckodriver --version

before_script:
  - foreman start &

script:
  - py.test --driver Firefox --base-url http://localhost:5000 --sensitive-url "utilityknife\.com" tests/

branches:
  only:
    - master
  
notifications:
  email:
    - mail@kevintechnology.com
