language: python

python:
  - "2.7"

services:
  - redis-server

before_install:
  - gem install foreman
  - pip install pytest

before_script:
  - foreman start &
  - sleep 3

script:
  - py.test tests/test_app.py
