language: python

python:
  - "2.7"

addons:
  chrome: stable

services:
  - redis-server

before_install:
  - gem install foreman
  - pip install -r dev_requirements.txt

before_script:
  - foreman start &
  - sleep 3

script:
  - py.test --driver Chrome --base-url http://localhost:5000 --sensitive-url "utilityknife\.com" tests/
